Προσθήκη Ανακοίνωσης "Μεταπτυχιακοί φοιτητές δικαιούχοι δωρεάν σίτισης ακαδ.έτους 2021-2022, τμημάτων με έδρα την Κέρκυρα"
ioniodi/all_collections pull request #14
Opened 2022-03-08 16:34 UTC by AimiliosPavlidis2001

*Σημείωση 1: Έχει γίνει close το pull request στο ioniodi/sitegr*
*Σημείωση 2: Οι σχετικοί συνεργάτες είναι οι ίδιοι με το προηγούμενο pull request*
*ΑΜ: Π2019053*

### Σχετικό Issue
closes [#248](https://github.com/ioniodi/sitegr/issues/248)

### Προτεινόμενες Αλλαγές
-- Αλλαγή 1: Έγινε προσθήκη της ανακοίνωσης "Μεταπτυχιακοί φοιτητές δικαιούχοι δωρεάν σίτισης ακαδ.έτους 2021-2022, τμημάτων με έδρα την Κέρκυρα"

[Demo σύνδεσμος](https://aimiliospavlidis2001-sitegr.netlify.app/posts/2022/03/05/metaptuxiakoi-sitish/)

Σχετικοί συνεργάτες: @p19pasc @u2nmd @vasiliskampani

### Υπενθυμίσεις
- [ ] Έχω ανοίξει από πριν issue για τον καλό συντονισμό του project, το οποίο έχει πάρει το πράσινο φως με την αντίστοιχη ετικέτα
- [ ] Έχω ενημερώσει το issueNo παραπάνω με τον αριθμό του αντίστοιχου θέματος, ώστε να κλείσει αυτόματα με την αποδοχή αυτού του αιτήματος
- [ ] Έχω δημιουργήσει branch για τις αλλαγές

2022-03-08 18:45 UTC, epidrome requested changes

2022-03-08 18:45 UTC, epidrome commented on _posts/2022-03-05-metaptuxiakoi-sitish.md
> +<br />
γιατί βάζεις κώδικα html σε αρχείο markdown?

αν θες να κάνεις μορφοποίηση να το κάνεις, αλλά με τρόπο συμβατό.

2022-03-08 19:38 UTC, AimiliosPavlidis2001 commented on _posts/2022-03-05-metaptuxiakoi-sitish.md
> +<br />
Ναι έχετε δίκιο δε το είχα προσέξει. Μόλις τροποποίησα το αρχείο και νομίζω πως διορθώθηκε. @epidrome

2022-03-10 23:59 UTC, AimiliosPavlidis2001 commented
@epidrome @diogenisAl η αλλαγή που μου ζητήθηκε έχει υλοποιηθεί επιτυχώς νομίζω, όταν μπορέσετε παρακαλώ ελέγξτε το αρχείο μου.

2022-03-13 15:09 UTC, epidrome commented
έχεις πολλά κομίτ κάνε squash

2022-03-13 15:43 UTC, AimiliosPavlidis2001 commented
> έχεις πολλά κομίτ κάνε squash

Νομίζω πως το squash έγινε επιτυχώς. @epidrome @diogenisAl

2022-03-13 16:15 UTC, merged