Προσθήκη Ανακοίνωσης " Ημερίδα Ενημέρωσης - "Έξυπνες ψηφιακές εφαρμογές και εργαλεία για την αποτελεσματική προώθηση και ανάδειξη της βιοποικοιλότητας των Ιονίων Νήσων - ΕΡΜΗΣ""
ioniodi/all_collections pull request #17
Opened 2022-03-08 20:54 UTC by initialelizah

Σχετικό Issue
closes https://github.com/ioniodi/sitegr/issues/275

Προτεινόμενες Αλλαγές
-- Πρόσθεσα την ανακοίνωση "Ημερίδα Ενημέρωσης - "Έξυπνες ψηφιακές εφαρμογές και εργαλεία για την αποτελεσματική προώθηση και ανάδειξη της βιοποικοιλότητας των Ιονίων Νήσων - ΕΡΜΗΣ"" στο all_collections/_posts/2022-01-26-hmerida-enhmerwshs.md.

Σχετικοί Συνεργάτες: @Vagelis1993 @rafael5gr2

### Υπενθυμίσεις
- [x] Έχω ανοίξει από πριν issue για τον καλό συντονισμό του project, το οποίο έχει πάρει το πράσινο φως με την αντίστοιχη ετικέτα
- [x] Έχω ενημερώσει το issueNo παραπάνω με τον αριθμό του αντίστοιχου θέματος, ώστε να κλείσει αυτόματα με την αποδοχή αυτού του αιτήματος
- [x] Έχω δημιουργήσει branch για τις αλλαγές

2022-03-08 21:25 UTC, epidrome commented
demo link?

2022-03-09 11:28 UTC, initialelizah commented
> demo link?

Το πρόσθεσα!

2022-03-10 18:09 UTC, Vagelis1993 approved these changes
Approved!

2022-03-13 15:21 UTC, epidrome requested changes

2022-03-13 15:21 UTC, epidrome commented on _posts/2022-01-26-hmerida-enhmerwshs.md
> +Περισσότερες πληροφορίες παρέχονται στην ιστοσελίδα της πλατφόρμας <https://ermis.di.ionio.gr/>
αυτό δεν είναι σωστή μορφή για σύνδεσμο σε markdown

2022-03-13 15:22 UTC, epidrome commented
τα περιττά κομίτ να γίνουν squash

2022-03-13 17:40 UTC, initialelizah commented
> τα περιττά κομίτ να γίνουν squash

Έγιναν οι αλλαγές.

2022-03-13 22:46 UTC, diogenisAl commented on _posts/2022-01-26-hmerida-enhmerwshs.md
> +https://ionio-gr.zoom.us/j/92735136977?pwd=K2FjdHh6MHd0R0JTcXcwV3l5VHpudz09
θα θέλαμε να δούμε και αυτόν τον σύνδεσμο σε markdown, όχι σαν απλό κείμενο

2022-03-14 11:08 UTC, initialelizah commented on _posts/2022-01-26-hmerida-enhmerwshs.md
> +https://ionio-gr.zoom.us/j/92735136977?pwd=K2FjdHh6MHd0R0JTcXcwV3l5VHpudz09
Έκανα την αλλαγή!

2022-03-14 16:56 UTC, merged