Προσθήκη ανακοίνωσης: Ενημέρωση Τμήματος από φοιτητές για κρούσμα Covid-19
ioniodi/all_collections pull request #18
Opened 2022-03-08 21:37 UTC by p18balt

### Σχετικό Issue
closes #269 

### Προτεινόμενες Αλλαγές
Έγινε η προσθήκη του σχετικού άρθρου για κρούσμα [covid](https://di.ionio.gr/gr/news/22818/)
Μπορείτε να δείτε την ανακοίνωση [εδώ](https://optimistic-kilby-7fd188.netlify.app/posts/2021/11/12/covid19-case/)(netlify Preview)
Ουσιαστικά έγινε η μεταφορά του αρχείου 2021-11-12-covid19-case.md στο submodule all_collections
Αξιολογητές: @p18kout ,@p18kana

2022-03-09 12:26 UTC, p18kout commented
Νομίζω πως τώρα είναι ολα όπως πρέπει συνάδελφε !

2022-03-09 12:29 UTC, p18kout approved these changes
Νομίζω πως τώρα είναι ολα όπως πρέπει συνάδελφε !

2022-03-11 15:31 UTC, p18kana commented
Νομιζω πως ειναι καλη η δουλεια σου!

2022-03-11 15:52 UTC, p18kana approved these changes
Νομιζω πως ειναι σωστη η δουλεια σου!

2022-03-11 19:52 UTC, epidrome requested changes

2022-03-11 19:52 UTC, epidrome commented on _posts/2021-11-12-covid19-case.md
> + - Κορωνοϊός
Αυτή η ετικέτα υπάρχει στην λίστα

2022-03-11 22:45 UTC, p18balt commented on _posts/2021-11-12-covid19-case.md
> + - Κορωνοϊός
Συγνώμη αλλά νομίζω το tag Κορωνοϊός δεν υπάρχει ακόμα και στα 2 άρθρα για covid στις ανακοινώσεις που υπάρχουν ήδη στο αποθετήριο
![Screen Shot 2022-03-12 at 00 42 18](https://user-images.githubusercontent.com/93882637/157984490-2c59dab5-c38a-4358-ab36-14163bf62a97.png)
![Screen Shot 2022-03-12 at 00 42 08](https://user-images.githubusercontent.com/93882637/157984498-b29559bd-fd57-4dec-b401-bcc6ea933287.png)
@epidrome διορθώστε με αν κάνω κάπου λάθος ευχαριστώ για τον χρόνο σας.

2022-03-13 14:57 UTC, epidrome commented on _posts/2021-11-12-covid19-case.md
> + - Κορωνοϊός
σωστά, άρα, πρέπει να γίνει πρώτα ξεχωριστή συζήτηση για να αποφασίσουμε αν/πως θα προστεθεί

για την ώρα καλύτερα να αφαιρεθεί

2022-03-13 15:57 UTC, p18balt commented on _posts/2021-11-12-covid19-case.md
> + - Κορωνοϊός
Το έχω κάνει ήδη πριν το σχόλιο σας και άφησα μόνο το γενικές ανακοινώσεις ευχαριστώ για την βοήθεια σας @epidrome

2022-03-13 16:21 UTC, epidrome requested changes

2022-03-13 16:21 UTC, epidrome commented on _posts/2021-11-12-covid19-case.md
> + - Γενικές Ανακοινώσεις
υπάρχει αυτή η ετικέτα στην ταξινόμηση;

2022-03-13 16:31 UTC, p18balt commented on _posts/2021-11-12-covid19-case.md
> + - Γενικές Ανακοινώσεις
Ναι υπάρχει

2022-03-13 16:36 UTC, epidrome commented on _posts/2021-11-12-covid19-case.md
> + - Γενικές Ανακοινώσεις
βοήθησε με γιατί δεν την βλέπω;
https://github.com/ioniodi/sitegr/wiki/Taxonomy

2022-03-13 16:45 UTC, p18balt commented on _posts/2021-11-12-covid19-case.md
> + - Γενικές Ανακοινώσεις
Συγνώμη λάθος μου δεν είχα διαβάσει τα παραπάνω πάντως βρίσκω το tag στο site . Κάνω τώρα τις απαραίτητες διορθώσεις. 
![Screen Shot 2022-03-13 at 18 41 30](https://user-images.githubusercontent.com/93882637/158069948-69092839-3bd5-4b46-8a6a-2e0b5b7a0f29.png)

2022-03-13 22:34 UTC, diogenisAl commented
@p18balt θα πρέπει να συμπληρώσεις και τα κατάλληλα checkboxes που λείπουν στο 1ο post

2022-03-14 17:08 UTC, merged