Ενημέρωση πληροφοριών για το μάθημα "Κοινωνικά και Νομικά Θέματα των ΤΠΕ"
ioniodi/all_collections pull request #23
Opened 2022-03-08 22:27 UTC by p19vrou

[Issue](https://github.com/ioniodi/sitegr/issues/276)

2022-03-12 15:37 UTC, epidrome requested changes

2022-03-12 15:37 UTC, epidrome commented on _courses/social-and-legal-issues-of-icts.md
> +author: atsohou hristope
είναι σίγουρα αυτός ο τρόπος εισαγωγής δύο καθηγητών σε ένα μάθημα σύμφωνα με παρόμοια αρχεία;

2022-03-12 15:37 UTC, epidrome commented on _courses/social-and-legal-issues-of-icts.md
> +author: atsohou hristope
είναι σίγουρα αυτός ο τρόπος εισαγωγής δύο καθηγητών σε ένα μάθημα σύμφωνα με παρόμοια αρχεία;

2022-03-12 15:40 UTC, epidrome commented
χρησιμοποίησε το pull_request_template.md

2022-03-13 22:16 UTC, diogenisAl commented
@p19vrou επίσης δεν έχεις βάλει σωστά το κείμενο που κλείνει το issue

2023-01-30 21:43 UTC, closed without merging